### ISSUE TITLE
hs upload error

### ISSUE THREAD

**Issue by ggosiang** [Hydrospheredata/hydro-serving#297]
I followed k8s installation to install using helm charts from repo, 
then all pods and deployments are running well.

Also, I installed hs-cli in version 2.0.6.

Currently, just followed this example to serve python model.
https://hydrosphere.io/serving-docs/latest/tutorials/python.html

But when I used `hs upload`
got errors,
```
Model definition composed:
{'contract': {'modelName': 'model',
              'predict': {'inputs': [{'dtype': 'DT_INT32',
                                      'name': 'number',
                                      'profile': 'NUMERICAL',
                                      'shape': {'dim': [{'name': '',
                                                         'size': -1}],
                                                'unknownRank': False}}],
                          'outputs': [{'dtype': 'DT_INT32',
                                       'name': 'number',
                                       'profile': 'NUMERICAL',
                                       'shape': {'dim': [{'name': '',
                                                          'size': -1}],
                                                 'unknownRank': False}}],
                          'signatureName': 'increment'}},
 'host_selector': None,
 'install_command': 'pip install -r requirements.txt',
 'metadata': {},
 'monitoring': None,
 'name': 'increment_model',
 'payload': ['/Users/ericyang/job/hydrosphere/increment_model/src',
             '/Users/ericyang/job/hydrosphere/increment_model/requirements.txt'],
 'runtime': {'name': 'hydrosphere/serving-runtime-python-3.6', 'tag': 'dev'},
 'training_data_file': None}
Traceback (most recent call last):
  File "/usr/local/bin/hs", line 10, in <module>
    sys.exit(hs_cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/hydroserving/cli/commands/root.py", line 92, in upload
    result = obj.model_service.apply(model, dir, no_training_data, ignore_monitoring)
  File "/usr/local/lib/python3.7/site-packages/hydroserving/core/model/service.py", line 106, in apply
    ignore_monitoring=ignore_monitoring
  File "/usr/local/lib/python3.7/site-packages/hydroserving/core/model/upload.py", line 100, in upload_model
    mv = upload_model_async(model_service, model, model_path)
  File "/usr/local/lib/python3.7/site-packages/hydroserving/core/model/upload.py", line 83, in upload_model_async
    logger.debug("Uploading model to %s", model_api.connection.remote_addr)
AttributeError: 'NoneType' object has no attribute 'remote_addr'
```

**Comment by ggosiang** [comment]
resolved it by myself.
need to add cluster firstly then do `hs upload`.

https://hydrosphere.io/serving-docs/latest/components/cli.html
