### ISSUE TITLE
S3SourceWatcher initialisation error

### ISSUE THREAD

**Issue by KineticCookie** [Hydrospheredata/hydro-serving#36]
```
[ERROR] a.a.OneForOneStrategy a.e.s.Slf4jLogger$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp.72 key not found: Records
java.util.NoSuchElementException: key not found: Records
    at scala.collection.MapLike$class.default(MapLike.scala:228) ~[scala-library-2.11.11.jar:?]
    at scala.collection.AbstractMap.default(Map.scala:59) ~[scala-library-2.11.11.jar:?]
    at scala.collection.MapLike$class.apply(MapLike.scala:141) ~[scala-library-2.11.11.jar:?]
    at scala.collection.AbstractMap.apply(Map.scala:59) ~[scala-library-2.11.11.jar:?]
    at io.hydrosphere.serving.manager.actor.modelsource.S3SourceWatcher$SQSMessage$.fromJson(S3SourceWatcher.scala:81) ~[manager.jar:0.0.1]
    at io.hydrosphere.serving.manager.actor.modelsource.S3SourceWatcher$$anonfun$2.apply(S3SourceWatcher.scala:25) ~[manager.jar:0.0.1]
    at io.hydrosphere.serving.manager.actor.modelsource.S3SourceWatcher$$anonfun$2.apply(S3SourceWatcher.scala:25) ~[manager.jar:0.0.1]
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[scala-library-2.11.11.jar:?]
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[scala-library-2.11.11.jar:?]
    at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) ~[scala-library-2.11.11.jar:?]
    at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) ~[scala-library-2.11.11.jar:?]
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:234) ~[scala-library-2.11.11.jar:?]
    at scala.collection.AbstractTraversable.map(Traversable.scala:104) ~[scala-library-2.11.11.jar:?]
    at io.hydrosphere.serving.manager.actor.modelsource.S3SourceWatcher.onWatcherTick(S3SourceWatcher.scala:25) ~[manager.jar:0.0.1]
    at io.hydrosphere.serving.manager.actor.modelsource.SourceWatcher$$anonfun$watcherTick$1.applyOrElse(SourceWatcher.scala:38) ~[manager.jar:0.0.1]
    at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170) ~[scala-library-2.11.11.jar:?]
    at akka.actor.Actor$class.aroundReceive(Actor.scala:513) ~[akka-actor_2.11-2.5.3.jar:?]
    at io.hydrosphere.serving.manager.actor.modelsource.S3SourceWatcher.aroundReceive(S3SourceWatcher.scala:17) ~[manager.jar:0.0.1]
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527) [akka-actor_2.11-2.5.3.jar:?]
    at akka.actor.ActorCell.invoke(ActorCell.scala:496) [akka-actor_2.11-2.5.3.jar:?]
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) [akka-actor_2.11-2.5.3.jar:?]
    at akka.dispatch.Mailbox.run(Mailbox.scala:224) [akka-actor_2.11-2.5.3.jar:?]
    at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.5.3.jar:?]
    at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [akka-actor_2.11-2.5.3.jar:?]
    at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [akka-actor_2.11-2.5.3.jar:?]
    at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [akka-actor_2.11-2.5.3.jar:?]
    at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [akka-actor_2.11-2.5.3.jar:?]
```

**Comment by KineticCookie** [comment]
## Investigation
Absence of `Records` field in message indicates that this is some kind of a service message. 
## Fix 
Implement SQS message filtration.
