### ISSUE TITLE
Oversized serving input

### ISSUE THREAD

**Issue by KineticCookie** [Hydrospheredata/hydro-serving#44]
For `data.json` file with 7.1 mb contents, manager fails to serve model.
Stacktrace:
```
[ERROR] i.h.s.m.c.ModelServiceController i.h.s.c.ServingDataDirectives$$anonfun$completeExecutionResult$2.apply.25 Serving failed
akka.http.scaladsl.model.EntityStreamSizeException: EntityStreamSizeException: actual entity size (Some(38515045)) exceeded content length limit (8388608 bytes)! You can configure this by setting `akka.http.[server|client].parsing.max-content-length` or calling `HttpEntity.withSizeLimit` before materializing the dataBytes stream.
	at akka.http.scaladsl.model.HttpEntity$Limitable$$anon$1.preStart(HttpEntity.scala:609) ~[akka-http-core_2.11-10.0.9.jar:?]
	at akka.stream.impl.fusing.GraphInterpreter.init(GraphInterpreter.scala:290) ~[akka-stream_2.11-2.5.3.jar:?]
	at akka.stream.impl.fusing.GraphInterpreterShell.init(ActorGraphInterpreter.scala:540) ~[akka-stream_2.11-2.5.3.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter.tryInit(ActorGraphInterpreter.scala:659) ~[akka-stream_2.11-2.5.3.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter.preStart(ActorGraphInterpreter.scala:707) ~[akka-stream_2.11-2.5.3.jar:?]
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:521) ~[akka-actor_2.11-2.5.3.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundPreStart(ActorGraphInterpreter.scala:650) ~[akka-stream_2.11-2.5.3.jar:?]
	at akka.actor.ActorCell.create(ActorCell.scala:591) ~[akka-actor_2.11-2.5.3.jar:?]
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462) ~[akka-actor_2.11-2.5.3.jar:?]
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484) ~[akka-actor_2.11-2.5.3.jar:?]
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282) ~[akka-actor_2.11-2.5.3.jar:?]
	at akka.dispatch.Mailbox.run(Mailbox.scala:223) ~[akka-actor_2.11-2.5.3.jar:?]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) ~[akka-actor_2.11-2.5.3.jar:?]
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [akka-actor_2.11-2.5.3.jar:?]
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [akka-actor_2.11-2.5.3.jar:?]
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [akka-actor_2.11-2.5.3.jar:?]
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [akka-actor_2.11-2.5.3.jar:?]
```
Note that log says that manager got 38515045 bytes, while data.json size is 7132595 bytes.

*Update*
This issue shows up when model runtime (in this case VGG 300 TF model) returns huge response.

## Fix
Set `akka.http.[server|client].parsing.max-content-length` parameter to ~100mb.

**Comment by ravimadhusudhan8** [comment]
When loading a large model - size >2GB - got this exception -

![stream-size-issue](https://user-images.githubusercontent.com/45240898/51394766-32a76e80-1b09-11e9-873c-70b1679122c2.PNG)

Then made the change to /manager/../application.conf 

![setting-in-app-conf-manager](https://user-images.githubusercontent.com/45240898/51394812-4ce14c80-1b09-11e9-9399-c3c52d115d1c.PNG)

Restarted Hydrosphere - still got the exception you see above. 

The limits set as shown below do not match the limits as seen in the stacktrace above ...

 http.server.parsing.max-content-length = 5000000000
  http.client.parsing.max-content-length = 5000000000

I am wondering if I am working with wrong conf file!

Thanks

**Comment by KineticCookie** [comment]
Hi. Sorry, I previously misunderstood your intents.

So, you made changes to the source code. You actually need to create a new manager image, delete the old manager container, and deploy the newest one.
1. Build manager image `sbt docker`
2. `docker rm -f manager` to delete the previous container,
3. `docker-compose up -d --no-deps manager` to create the newer container without touching the remaining infrastructure.

**Comment by KineticCookie** [comment]
I will reopen the issue to keep my tab open on your issue.

**Comment by ravimadhusudhan8** [comment]
Thanks!
