### ISSUE TITLE
Getting error when trying to launch latest code.

### ISSUE THREAD

**Issue by tylerfordML** [Hydrospheredata/hydro-serving#68]
the code keeps hanging on on this line. 

package io.hydrosphere.serving.manager.service.clouddriver
 val containerApp = map.getOrElse(DEPLOYMENT_TYPE_APP, throw new RuntimeException(s"Can't find APP for service $serviceId in $seq"))
    val containerModel = map.get(DEPLOYMENT_TYPE_MODEL)

here are the logs 

Detected a modification of naivebayes model ...

2018-02-02T02:04:08.904425412Z [ERROR] a.a.OneForOneStrategy a.e.s.Slf4jLogger$$anonfun$receive$1$$anonfun$applyOrElse$1.apply$mcV$sp.69 ****Can't find APP for service -20 in**** ArrayBuffer(Container{id=943746c801f22a7327046483fe2e902cd7a140e81d2c30b0b60237668662f6f5, names=[/manager], image=hydrosphere/serving-manager:latest, imageId=sha256:5b64769a1afaec201315228f129c68f9d748d17dcb8892336c1265b6d4995f5a, command=/hydro-serving/app/start.sh, created=1517537030, state=running, status=Up 15 seconds, ports=[PortMapping{privatePort=8080, publicPort=8080, type=tcp, ip=0.0.0.0}, PortMapping{privatePort=8081, publicPort=8081, type=tcp, ip=0.0.0.0}, PortMapping{privatePort=8082, publicPort=8082, type=tcp, ip=0.0.0.0}, PortMapping{privatePort=9090, publicPort=9090, type=tcp, ip=0.0.0.0}, PortMapping{privatePort=9091, publicPort=9091, type=tcp, ip=0.0.0.0}], labels={APP=dev, HS_SERVICE_MARKER=HS_SERVICE_MARKER, MODEL=dev, MODEL_NAME=manager, MODEL_VERSION=latest, RUNTIME_TYPE_NAME=hysroserving-java, RUNTIME_TYPE_VERSION=latest, com.docker.compose.config-hash=4f0db1769543bf239bc78c5d86bec95419c1333fcf20860c1c3d919a4b84c3a3, com.docker.compose.container-number=1, com.docker.compose.oneoff=False, com.docker.compose.project=automation, com.docker.compose.service=manager, com.docker.compose.version=1.18.0, hydroServingServiceId=-20}, sizeRw=null, sizeRootFs=null, networkSettings=NetworkSettings{ipAddress=null, ipPrefixLen=null, gateway=null, bridge=null, portMapping=null, ports={}, macAddress=null, networks={automation_extnet=AttachedNetwork{aliases=null, networkId=691539ea57f31850a906f68150bcfeb7b6df61185ed71fb22fe20a8e1979927d, endpointId=172441d34b4990d656433199d99d1fa8b2ddec1d2cbf1ab05d391939486c975f, gateway=172.18.0.1, ipAddress=172.18.0.3, ipPrefixLen=16, ipv6Gateway=, globalIPv6Address=, globalIPv6PrefixLen=0, macAddress=02:42:ac:12:00:03}, automation_hydronet=AttachedNetwork{aliases=null, networkId=0946e51564a0333f2444f003060769f38bb5fc2cc541e1199a82f3aeb4aefe9a, endpointId=edec4e1ab6ef73e279cd22dd9c785554c10ee8a5cd87f0bace72f2d899f30b81, gateway=172.16.0.1, ipAddress=172.16.0.5, ipPrefixLen=24, ipv6Gateway=, globalIPv6Address=, globalIPv6PrefixLen=0, macAddress=02:42:ac:10:00:05}}, endpointId=null, sandboxId=null, sandboxKey=null, hairpinMode=null, linkLocalIPv6Address=null, linkLocalIPv6PrefixLen=null, globalIPv6Address=null, globalIPv6PrefixLen=null, ipv6Gateway=null}, mounts=[ContainerMount{type=bind, name=null, source=/opt/hydro-serving/integrations/automation/hydro-serving-runtime/models, destination=/models, driver=null, mode=rw, rw=true, propagation=rprivate}, ContainerMount{type=bind, name=null, source=/var/run/docker.sock, destination=/var/run/docker.sock, driver=null, mode=rw, rw=true, propagation=rprivate}]})
z2018-02-02T02:04:08.904474888Z akka.actor.ActorInitializationException: akka://manager/user/$e: exception during creation
2018-02-02T02:04:08.904478772Z 	at akka.actor.ActorInitializationException$.apply(Actor.scala:193) ~[akka-actor_2.11-2.5.8.jar:?]
s2018-02-02T02:04:08.904481451Z 	at akka.actor.ActorCell.create(ActorCell.scala:608) ~[akka-actor_2.11-2.5.8.jar:?]
w2018-02-02T02:04:08.904483738Z 	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:462) [akka-actor_2.11-2.5.8.jar:?]
x2018-02-02T02:04:08.904485976Z 	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:484) [akka-actor_2.11-2.5.8.jar:?]
2018-02-02T02:04:08.904488321Z 	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282) [akka-actor_2.11-2.5.8.jar:?]
n2018-02-02T02:04:08.904490581Z 	at akka.dispatch.Mailbox.run(Mailbox.scala:223) [akka-actor_2.11-2.5.8.jar:?]
o2018-02-02T02:04:08.904492783Z 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234) [akka-actor_2.11-2.5.8.jar:?]
2018-02-02T02:04:08.904495002Z 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [akka-actor_2.11-2.5.8.jar:?]
2018-02-02T02:04:08.904497252Z 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [akka-actor_2.11-2.5.8.jar:?]
2018-02-02T02:04:08.904499506Z 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [akka-actor_2.11-2.5.8.jar:?]
2018-02-02T02:04:08.904501736Z 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [akka-actor_2.11-2.5.8.jar:?]

**Comment by Zajs** [comment]
Fixed this issue in #71, please look for details here #67
